version: '2.4'

volumes:
  notes: {}

services:

  py:
    image: continuumio/anaconda:2019.07-alpine
    volumes:
      - notes:/opt/notebooks
    command: sh -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"
    restart: unless-stopped
    ports:
      - 8888:8888/tcp

