version: '2.4'

volumes:
  notes: {}

services:

  py:
    image: continuumio/anaconda3:2019.10-alpine
    volumes:
      - notes:/opt/notebooks
    container_name: jupyter
    command: /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --allow-root --port=8888 --no-browser
    restart: unless-stopped
    ports:
      - 8888:8888/tcp
